pool:
  vmImage: 'Ubuntu 16.04'

pr: none 
  
variables:
  buildConfiguration: 'Release'

jobs:
- job: Install SonarCloud
  steps:
  - script: dotnet tool install --global dotnet-sonarscanner
- job: Init SonarCloud Scan
  steps:
  - script: $HOME/.dotnet/tools/dotnet-sonarscanner begin /k:"$(SONAR_PROJECT_KEY)" /o:"$(SONAR_ORGANIZATION)" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(SONAR_TOKEN)"
- job: Run Build
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
- job: Run Unit Tests (xUnit)
  steps:
  - script: dotnet test --configuration $(buildConfiguration) --no-build
- job: Finish SonarCloud Scan
  steps:
  - script: $HOME/.dotnet/tools/dotnet-sonarscanner end /d:sonar.login="$(SONAR_TOKEN)"